sudo: required
dist: trusty
language: node_js
node_js: stable

env:
  global:
    - CC_TEST_REPORTER_ID=2271c34d4b24dab2d2867860133a62654442f637117c09195c7f6bb349073033

git:
  depth: 3
  lfs_skip_smudge: true

notifications: 
  email: false

cache:
  directories: node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
  codeclimate:
    repo_tohen: 2271c34d4b24dab2d2867860133a62654442f637117c09195c7f6bb349073033

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: 
  - npm install
  - npm install codeclimate-test-reporter
  - npm install -g angular-cli
  - npm install -g karma

before_script:
  #- npm install -g codecov
  #- npm install coveralls
  - ng lint
  - ng build --aot --prod
  - ng serve & ng e2e

script:
- ng test --code-coverage --watch=false

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - codeclimate-test-reporter < coverage/lcov.info