sudo: required
dist: trusty
language: node_js
node_js: stable

git:
  depth: 3
  lfs_skip_smudge: true

notifications: 
  email: false

cache:
  directories: node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
  code_climate:
      repo_token: 787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d 

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: 
  - npm install
  - npm install codeclimate-test-reporter
  - npm install -g angular-cli
  - npm install -g karma

before_script:
  #- npm install -g codecov
  #- npm install coveralls
  - ng lint
  - ng build --aot --prod
  - ng serve & ng e2e

script:
- ng test --code-coverage --watch=false

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - codeclimate-test-reporter < coverage/lcov.info