sudo: required
dist: trusty
language: node_js
node_js: stable

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

git:
  depth: 3
  lfs_skip_smudge: true

notifications: 
  email: false

cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
#- npm install -g codecov
#- npm install coveralls
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng lint
- ng build --aot --prod
- ng serve & ng e2e
#- ng test --watch=false --code-coverage

script: 
#- codecov
#- cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
- ng test --code-coverage --watch=false

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
